server:
  port: 8082

spring:
  application:
    name: Yasuo Application
  datasource:
    url: jdbc:postgresql://localhost:5443/yasuo
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/



logging:
  level:
    org.hibernate:
      sql: debug
      type: trace












